# Generated by Django 5.0.4 on 2024-05-08 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_alter_purchaseorder_quality_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vender',
            name='average_response_time',
            field=models.DateTimeField(default=0),
        ),
    ]
