# Generated by Django 5.0.4 on 2024-05-08 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_alter_vender_average_response_time'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vender',
            new_name='Vendor',
        ),
    ]
